### ISSUE TITLE
fps and pose estimation

### ISSUE THREAD

**Issue by ifangcheng** [TuSimple/mx-maskrcnn#1]
1. When do inference, can it achieve 5+fps?
2. The current version supports pose estimation?

**Comment by Zehaos** [comment]
1. We got 2~3 fps with 1024*2048 input (1080ti, cityscapes).
2. The current version doesn't support pose estimation.

**Comment by kli-nlpr** [comment]
Will ROIAlign be merged into offical mxnet?

**Comment by hdjsjyl** [comment]
@Zehaos , If I want the current version to support keypoint detection, what should I do? Any advice will be appreciated. Thank you.
