### ISSUE TITLE
ImportError：No module named bbox

### ISSUE THREAD

**Issue by miraclewkf** [TuSimple/mx-maskrcnn#10]
When I run `train_alternate_mask_fpn.py`, I get this error: `ImportError：No module named bbox`. I check there is the script in `/mx-maskrcnn/rnn/cython/bbox.pyx`, but I don't know why it can't import this script? It is the reason of `.pyx`?

**Comment by Zehaos** [comment]
Run make command in the root folder to build the related cython code.

**Comment by miraclewkf** [comment]
Run `make` in `/mx-maskrcnn` and get `ImportError: No module named Cython.Distutils` and 'ImportError: No module named Cython.Build'

**Comment by Zehaos** [comment]
There are some [requirements](https://github.com/TuSimple/mx-maskrcnn#requirement) should be installed first.
