### ISSUE TITLE
How can I download the cityscape database?

### ISSUE THREAD

**Issue by tzhang2014** [TuSimple/mx-maskrcnn#11]
How can I download the cityscape database? THX

**Comment by Zehaos** [comment]
You should regist and then apply for it in https://www.cityscapes-dataset.com/.

**Comment by huyangc** [comment]
just search it on google please. You need other to feed everything into your mouth?

**Comment by tzhang2014** [comment]
@Zehaos I do it ,But it take a couple days .

**Comment by tzhang2014** [comment]
@huyangc 　ｗｈａｔ does it matter to you?
