### ISSUE TITLE
Is it reasonable to set the PIXEL_MEANS in rcnn/config.json file to (0,0,0)?

### ISSUE THREAD

**Issue by Geekking** [TuSimple/mx-maskrcnn#113]
[PIXEL_MEANS](https://github.com/TuSimple/mx-maskrcnn/blob/a74c567b646f6f151fe5b39bd26f8a73d3041716/rcnn/config.py#L139) variable in rcnn/config.json

**Comment by huangzehao** [comment]
The first BN layer does the things of extracting mean and dividing variance.
https://github.com/TuSimple/mx-maskrcnn/blob/master/rcnn/symbol/symbol_mask_fpn.py#L37

**Comment by githubfragments** [comment]
If I understand, there still has the problem, given the "use_global_stats = True". What do you think? @huangzehao
