### ISSUE TITLE
Full of errors.

### ISSUE THREAD

**Issue by jinfagang** [TuSimple/mx-maskrcnn#12]
Thanks for this "Wonderfull" opensource, but I have to say the codes are really shit. I opened a issue reported a bug and return a commit point, after I tried it, same errors happen again. Too simple the technical people.

**Comment by jinfagang** [comment]
I think this code not worth to waste time, just for the rest coming developers.

**Comment by zhanghan328** [comment]
I tried, got the same problem.

**Comment by winstywang** [comment]
If you don't like it, you could reproduce the paper by yourself. Issues are use to report bugs and improve the repo. We don't welcome such meanless and unfriendly complains.

**Comment by jinfagang** [comment]
If you guys not prepare the codes well, then better keep it in your home bed. You are on behalf your company not yourself, careful of your way threat problems.

**Comment by winstywang** [comment]
We tried in several environments, it works well. We believe it can only be reproduced in certain environment. If you met problems, the right way is to analyze the problems, and we would like to help. The complain in your style is really a waste of time.
