### ISSUE TITLE
why bn_data_moving_var is so large after training the model

### ISSUE THREAD

**Issue by gaosanyuan** [TuSimple/mx-maskrcnn#127]
After training the model, I found that the bn_data_moving_var is large, [4884.816 4603.264 4990.553] in my case; also the other moving vars is much smaller, such as stage3_unit3_bn1_moving_var(
[0.00838549 0.00935058 0.00836632 ... 0.01761703 0.00871543 0.01058431]), is it normal?
Thanks

**Comment by huangzehao** [comment]
It is normal. The bn_data layer is used for data preprocessing. The output of bn_data layer is [input - moving_mean / sqrt(moving_var) * gamma + beta]. Gamma = 1 since we set fix_gamma = True.

**Comment by gaosanyuan** [comment]
I checked that in demo_single_image, the input of the image does not subtract the pixel means (I believe that the mean of pixels should be subtracted as the training process do ), which also can lead a not bad result. I think the main reason comes from the large bn_data_moving_var.
@huangzehao

**Comment by huangzehao** [comment]
The bn_data layer plays an role like image preprocessing. So we don't need to do image preprocessing by ourselves.

**Comment by githubfragments** [comment]
The "use_global_stats" term is set to True. So the net used the statistics of ImageNet. Subtracting the mean of pixels or not should have a big different result. Is that right? @huangzehao
