### ISSUE TITLE
The number of sampled regular locations

### ISSUE THREAD

**Issue by xmyqsh** [TuSimple/mx-maskrcnn#13]
The number of sampled regular locations in your [implementation](https://github.com/TuSimple/mx-maskrcnn/blob/master/rcnn/CXX_OP/roi_align.cu#L72-#L73) seems 3.
```
Dtype h_stride = (hend - hstart)/3.0;
Dtype w_stride = (wend - wstart)/3.0;
```
But the author samples 4 regular locations.

Is 3 better than 4?
Do you observe diminishing as the number of regular locations increase?

**Comment by Zehaos** [comment]
Hi, xmyqsh

We sampled 4 points. Look at here [roi_align.cu#L204-L205](https://github.com/TuSimple/mx-maskrcnn/blob/master/rcnn/CXX_OP/roi_align.cu#L204-L205).

**Comment by xmyqsh** [comment]
@Zehaos 
Forgive me.
Got it.
2 * 2 = 4

**Comment by Zehaos** [comment]
@xmyqsh You are welcome.
