### ISSUE TITLE
About multi-scale training

### ISSUE THREAD

**Issue by xmyqsh** [TuSimple/mx-maskrcnn#14]
There is [multi-scale training](https://github.com/TuSimple/mx-maskrcnn/blob/master/rcnn/config.py#L35) in your implementation.
```
config.TRAIN.SCALE_RANGE = (0.8, 1)
```
But the author resizes the shorter edge to 800 pixels on coco and 2048×1024 pixels on Cityscapes.

The FPN backend should have a good scale invariant ability(I'm not sure this description is proper or not).

Just looking forward single scale training result.

**Comment by Zehaos** [comment]
The author do use multi-scale training in there implementation to reduce overfitting (Cityscape dataset(fine only) only has 3000 pictures). We haven't tried single scale training.

**Comment by Zehaos** [comment]
@xmyqsh Please refer to page 9, Experiments on Cityscapes.

**Comment by xmyqsh** [comment]
haha, you are right.

Multi-scale on Cityscape reduces overfitting.
And fixed 800 pixels on coco.

Good job.
