### ISSUE TITLE
Speed drop when training?

### ISSUE THREAD

**Issue by rxqy** [TuSimple/mx-maskrcnn#143]
Speed would drop when training RPN.
I'm using 2 TITANX, with BATCH_SIZE set to 1
can have about \~2 samples at the beginning, but would drop to 0.6~0.9 later, stuck in epoch 0.
I'm the only one using the gpu... the volatile may drop to zero suddenly.
Guess it's speeding too much time loading data?

**Comment by zl1994** [comment]
According to my experience, maybe there are other programs running out CPU resources and it will influence the speed of feeding data to GPU.

**Comment by rxqy** [comment]
ehhh Don't know for sure. It's strange
Now I set a lower nice value, -5, to the process.
and I think I'm the only one using the cpu by htop or top.
