### ISSUE TITLE
AttribuuteError:  'module' object has no attribute 'ROIAlign'

### ISSUE THREAD

**Issue by qinb** [TuSimple/mx-maskrcnn#15]
thanks

**Comment by Zehaos** [comment]
Hi, @qinb
Please refer to [Preparation for training](https://github.com/TuSimple/mx-maskrcnn#preparation-for-training) Step 3.

**Comment by ChenFengYe** [comment]
I do follow your step 3.
Step like below
`git clone --recursive https://github.com/apache/incubator-mxnet.git incubator-mxnet --branch 0.11.0`
`cp rcnn/CXX_OP/* incubator-mxnet/src/operator/`
`cd incubator-mxnet`
`make -j USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1`
`cd ..`
`make`
'bash scripts/train_alternate.sh'
However, I still get this error. I do't where is wrong....

**Comment by huangzehao** [comment]
@ChenFengYe 
Hi, did you install mxnet python interface?

https://github.com/apache/incubator-mxnet/blob/master/setup-utils/install-mxnet-ubuntu-python.sh#L47

**Comment by ChenFengYe** [comment]
Thanks! You are really a nice guy!

But It shows these message ... I am really not familiar with mxnet.

`[19:13:51] src/operator/././cudnn_algoreg-inl.h:117: If you see this message in the middle of training, you are probably using bucketing. Consider set
ting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable cudnn tuning.`

**Comment by Zehaos** [comment]
@ChenFengYe , Please use command below to clone. There is a bug in mxnet 0.11.
```
git clone --recursive https://github.com/apache/incubator-mxnet.git incubator-mxnet
```

**Comment by Zehaos** [comment]
@ChenFengYe , Please use command below to clone, we have specified a version of mxnet as submodule. There is a bug in mxnet 0.11.
```
git clone --recursive https://github.com/TuSimple/mx-maskrcnn
```

**Comment by qinb** [comment]
thank you very much,  I solved it

**Comment by DamongZ** [comment]
HI @qinb , I get the same error, can you tell me how to fix it. thanks

**Comment by qinb** [comment]
actually, I download the different mxnet version. you could git clone --recursive https://github.com/TuSimple/mx-maskrcnn as @Zehaos  said.

**Comment by DamongZ** [comment]
@qinb I solved it. thanks

**Comment by DevinCheung** [comment]
@qinb Hi, I met this error during training (after generating RPN detection). Does 'git clone --recursive https://github.com/TuSimple/mx-maskrcnn' mean that I need to redownload the whole code repositories and restart from step 1? Thanks!

**Comment by DevinCheung** [comment]
@Zehaos @huangzehao I met this error ''module' object has no attribute 'ROIAlign'' when running "########## TRAIN RCNN WITH IMAGENET INIT AND RPN DETECTION" step. And I didn't not build MXNet from source. I install mxnet by "pip" and the version is 0.12.1. Is there anything wrong?

**Comment by Zehaos** [comment]
@DevinCheung 
You should build mxnet from sources. Please refer to FAQ.

**Comment by DevinCheung** [comment]
@Zehaos Hi, I am a little confused. Should I build mxnet from sources to the /mx-maskrcnn/incubator-mxnet? Or anywhere is ok?

**Comment by DevinCheung** [comment]
@qinb which mxnet version did you download?

**Comment by qinb** [comment]
@DevinCheung you follow this step:  git clone --recursive https://github.com/TuSimple/mx-maskrcnn
I solved it by this step

**Comment by DevinCheung** [comment]
@qinb I met the error "/usr/lib/liblapack.so.3: undefined symbol: gotoblas" when I build the mxnet. Have you met this?

**Comment by qinb** [comment]
@DevinCheung  I dont meet this problem.  But it shows that "/usr/lib/liblapack.so.3: undefined symbol: gotoblas"，so you could consult by yourself.
