### ISSUE TITLE
Step 3 fix

### ISSUE THREAD

**Issue by umyta** [TuSimple/mx-maskrcnn#151]
When I built this on linux 16.04 recently, I noticed that for step 3, it should be: 
`cp rcnn/CXX_OP/* incubator-mxnet/src/operator/contrib/`

Otherwise, I get the following errors:

`build/src/operator/roi_align.o: In function `mxnet::op::ROIAlignParam::__MANAGER__()':
roi_align.cc:(.text+0x1310): multiple definition of `mxnet::op::ROIAlignParam::__MANAGER__()'
build/src/operator/contrib/roi_align.o:roi_align.cc:(.text+0x2ac0): first defined here
build/src/kvstore/kvstore_utils_gpu.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
Makefile:525: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1
make: *** Waiting for unfinished jobs....
build/src/operator/roi_align.o: In function `mxnet::op::ROIAlignParam::__MANAGER__()':
roi_align.cc:(.text+0x1310): multiple definition of `mxnet::op::ROIAlignParam::__MANAGER__()'
build/src/operator/contrib/roi_align.o:roi_align.cc:(.text+0x2ac0): first defined here
collect2: error: ld returned 1 exit status
Makefile:496: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1
`

**Comment by firstlove1208** [comment]
I got the same problem, did you fix that? Thanks a lot.
