### ISSUE TITLE
Error in "_make_data_and_labels" -- Use my dataset to train net 

### ISSUE THREAD

**Issue by ChenFengYe** [TuSimple/mx-maskrcnn#17]
I convert my dataset to the type of cityscapes to use this net. Of course, I modify several palaces for file index of dataset and class_id.
However, the training gets crashed after achieving the first training part of RPN. 
The  crash happend in  
`data_on_imgs['img_%s' % im_i]['bbox_targets_on_levels']['stride%s' % s] = np.concatenate([_bbox_targets, bbox_targets_pad])`

`data_on_imgs['img_%s' % im_i]['bbox_weights_on_levels']['stride%s' % s] = np.concatenate([_bbox_weights, bbox_weights_pad])`

**File "mx-maskrcnn/rcnn/core/loader.py", line 278, in _make_data_and_labels**
`ValueError: all the input array dimensions except for the concatenation axis must match exactly`

PS: I check the pairs of corresponding img and label, they all get the same size in pairs.

Really Thank you guys for these a lot of help!

**Comment by ChenFengYe** [comment]
I find the key point of this problem  is 
`Import rcnn.Config as Config` 
I build my own file named 'Config_my'and change
`from rcnn.config import config, default, generate_config`
to
`from rcnn.config_my import config, default, generate_config`
without notice that ** this config is reloaded many time in different file **.

So I just change the config instead, Hope you guys can avoid this problem.

**Comment by napolun279** [comment]
@ChenFengYe 
hello! I encounter this problem as yours, and I try to put "from rcnn.Config import config, default, generate_config" into loader.py and train_alternate_mask_fpn.py, but I still have this error, so I want to know wether I should put this into some other files? or can you tell me how did you change your "Config_my"? 
Any advice will be much appreciated. Thanks!

**Comment by ChenFengYe** [comment]
Firstly, You should build your own config, and name it with "config_my ". The detail about changing it to your own config depends on your dataset. (put "config_my " file into rcnn/ folder)
Then, Your should change all 

>"from rcnn.Config import config“ 

to

>"from rcnn.config_my import config“ 

in this whold project.

Or,
you can simply change the "Config" file to meet your dataset condition.

**Comment by napolun279** [comment]
@ChenFengYe 
ok,I will have a try, thank you very much!
