### ISSUE TITLE
Demo Test got all " NAN scores"

### ISSUE THREAD

**Issue by ChenFengYe** [TuSimple/mx-maskrcnn#19]
Emm.... I propose issue again...
My dataset is 5 classes. There are several terms of my config.
> config.NUM_CLASSES = 5
> config.SCALES = [(1024, 2048)]
> config.CLASS_ID = [0, 1, 2, 3, 4]
> config.TRAIN.SCALE = True   (!!! This term you never use in your project!!!)
> default.rpn_epoch = 4
> default.rcnn_epoch = 12
> dataset.ObjectSnap.NUM_CLASSES = 5
> dataset.ObjectSnap.CLASS_ID = [0, 1, 2, 3, 4]
> dataset.ObjectSnap.SCALES = [(1024, 2048)]

I build a small dataset with 41 images for verification. The net is trained well. Parts of my Log:
> Epoch[2] Batch [20]	Speed: 10.90 samples/sec	Train-RPNAcc=0.903181,	RPNLogLoss=0.238827,	RPNL1Loss=0.933737,	
Epoch[2] Batch [40]	Speed: 12.69 samples/sec	Train-RPNAcc=0.919255,	RPNLogLoss=0.200416,	RPNL1Loss=0.927370,	
Epoch[2] Train-RPNAcc=0.919255
Epoch[2] Train-RPNLogLoss=0.200416
Epoch[2] Train-RPNL1Loss=0.927370
Epoch[2] Time cost=7.387

> Epoch[0] Batch [20]	Speed: 1.18 samples/sec	Train-RCNNAcc=0.936756,	RCNNLogLoss=0.921319,	RCNNL1Loss=1.693366,	MaskACC=0.981722,	MaskLogLoss=0.033281,	
> Epoch[0] Batch [40]	Speed: 1.28 samples/sec	Train-RCNNAcc=0.946408,	RCNNLogLoss=0.617575,	RCNNL1Loss=1.681111,	MaskACC=0.983959,	MaskLogLoss=0.030308,	
> Epoch[0] Train-RCNNAcc=0.946408
> Epoch[0] Train-RCNNLogLoss=0.617575
> Epoch[0] Train-RCNNL1Loss=1.681111
> Epoch[0] Train-MaskACC=0.983959
> Epoch[0] Train-MaskLogLoss=0.030308
> Epoch[0] Time cost=67.991

Finally, I get my final-0000.params model
However! When I use several images in my train lists, I got all NAN scores for both my demo test and evaluation test. Jesus! How could that happen??

PS: One more doubt point, the log shows I get a very high Acc (like 0.8~0.9) even at the very beginning of my training!

Hope get your reply soon~ Thanks~

**Comment by qinb** [comment]
do you meet this problem? 
cityscape_train gt roidb loaded from model/res50-fpn/cityscape/alternate/cache/cityscape_train_gt_roidb.pkl
[08:00:27] ~/mx-maskrcnn/incubator-mxnet/dmlc-core/include/dmlc/logging.h:308: [08:00:27] src/operator/./cudnn_convolution-inl.h:419: Check failed: e == CUDNN_STATUS_SUCCESS (3 vs. 0) cuDNN: CUDNN_STATUS_BAD_PARAM

thank you very much!

**Comment by ChenFengYe** [comment]
@qinb Oh, do I use that poor description... Sorry for confusing you.
I already get my trained model. There is no error to crash.  The problem happened in 
> bash scripts/demo.sh
and it is no a crash. I do get my tested images. But they have no instances on it. By debugging, I find the output of network `output['cls_prob_reshape_output']` in `core.tester--im_detect_mask` are all NAN.

**Comment by qinb** [comment]
sorry, I don't run this step yet

**Comment by ChenFengYe** [comment]
@qinb You can try my compiled mxnet  #8  might help....

**Comment by Zehaos** [comment]
@ChenFengYe 
config.TRAIN.SCALE must be removed accidently. I will double check tomorrow. Thanks.
I suggest you to check whether you have make a right instance seg label image as cityscape did for your dataset.

**Comment by tonysy** [comment]
@qinb  please check your cudnn version when you met 'cudnn_convolution-inl.h:419: Check failed: e == CUDNN_STATUS_SUCCESS (3 vs. 0) cuDNN: CUDNN_STATUS_BAD_PARAM'

I got the same error when use  cudnn 5.1, and update cudnn to 6 works for me.

**Comment by ChenFengYe** [comment]
@Zehaos I find that you change the scale of Images. However, where do you change the scale fo rpn annotation(box) and rcnn annotation(mask)

**Comment by ChenFengYe** [comment]
I think this error may cause by un-flip mask error. 
I fully suggest newcomer take care of this error and do not set too small short-side of Config.SCALE. (above 800 suggested)
Thanks the advice from @Zehaos

**Comment by hdjsjyl** [comment]
@ChenFengYe , Hi, I am using the wider face dataset to train the rpn part. First, all images in the cityscapy have the same size(1024.2048), but for wider face, the sizes are different, Now I set (3072,1024), It's still training. How you solve the problem about testing NAN problem? Do you give me some advice about fitting own dataset to train maskrcnn?

**Comment by ChenFengYe** [comment]
@hdjsjyl  I think the scale of your datasets satisfies "Above 800".  The error happened here may be caused by not flipping the mask while flipping the image.

This code error is fixed in "afd4ca333ee4c9f9b39da35fd4d787c2b43da31e" commit

https://github.com/TuSimple/mx-maskrcnn/commit/afd4ca333ee4c9f9b39da35fd4d787c2b43da31e

Make sure you get this fixed, then just try it.
Good luck!

**Comment by hdjsjyl** [comment]
@ChenFengYe , thanks for your answers. I have another question.  whether the image sizes of dataset should be the same like cityscapes dataset. If one biggest size of images in my own dataset is 7127*7172, when I set the max_shape, it always has error for cuda memory fail. Thanks.

**Comment by ChenFengYe** [comment]
@hdjsjyl There is no requirement for using the same size of cityscape dataset. I think your image size  7127*7172 is really so huge! How big your datasets are?  You must be sure that your GPU memory can hold that! If not the memory would fail!

**Comment by hdjsjyl** [comment]
@ChenFengYe , my dataset just has about 2.5G, but the size varies from 500*1000 to 7000*7000. I want to use it to train the mask rcnn. In the code, it has inferred shape of image and maximum shape of image. So I don't know how to cope with it. Thanks
