### ISSUE TITLE
check failed: e == cuDNN: CUDNN_STATUS_BSUCCESS(3 vs. 0) cuDNN: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by qinb** [TuSimple/mx-maskrcnn#20]
now, I meet the new problem as about.  I guesss that cudnn's version is different. 
in order to avoid this error,  could I not to use cudnn when i compile mxnet?

**Comment by Zehaos** [comment]
Hi, @qinb 
Of course you can. If there is other errors occur, feel free to tell us.

**Comment by winstywang** [comment]
Close due to inactive status. Please reopen it if needed.
