### ISSUE TITLE
fail to "make"

### ISSUE THREAD

**Issue by DevinCheung** [TuSimple/mx-maskrcnn#21]
When I build related cython code in step 4, I encountered the following error:
![bug1](https://user-images.githubusercontent.com/22792747/32144198-1cb936ee-bcf0-11e7-8720-dc25f627983b.png)
![bug2](https://user-images.githubusercontent.com/22792747/32144203-232d7e2c-bcf0-11e7-843d-4d9fa125e442.png)

How could I solve it?
Thanks!

**Comment by Zehaos** [comment]
Hi, @DevinCheung 
What's the g++ version you used? I think it is caused by a lower version of compiler. You could switch to a newer one and try again.

**Comment by DevinCheung** [comment]
Hi, @Zehaos
My g++ version is 5.4. The error is about '-R'. Is that caused by g++ ?

**Comment by yingning** [comment]
Hi, @DevinCheung ,I got the same error, have you solved the problem? Any help will be appreciated ! Meanwhile my g++ version is also 5.4.

**Comment by huangzehao** [comment]
Hi, @DevinCheung @yingning 
Please refer https://github.com/rbgirshick/py-faster-rcnn/issues/706 and try if the solution solve your problem.

**Comment by yingning** [comment]
@huangzehao ,Thank you for your kind heart ,your suggestion help me solved this problem!
