### ISSUE TITLE
compile mxnet error with cuda 8.0

### ISSUE THREAD

**Issue by cgangEE** [TuSimple/mx-maskrcnn#25]
/home/cgangee/code/mxnet/mshadow/mshadow/./base.h:371:43: error: ‘CUDA_R_32I’ was not declared in this scope
   static const cudaDataType_t kCudaFlag = CUDA_R_32I;

**Comment by Zehaos** [comment]
Please refer to https://github.com/apache/incubator-mxnet/issues/6245

**Comment by cgangEE** [comment]
@Zehaos Thanks, Do you know any method to visit google in mainland China?
