### ISSUE TITLE
Can not access model on dropbox anymore

### ISSUE THREAD

**Issue by Tetsujinfr** [TuSimple/mx-maskrcnn#26]
Hi,
I could see the drop box link about 2h ago on my mobile, but when I tried again now to download it, the site can not be accessed anymore, whether from PC or mobile.  Is the link de-activated or cancelled? Can you repost the param file somewhere else?
Thanks
Tets

**Comment by Zehaos** [comment]
The link is fine. Please check your network or try [BaiduYun](https://pan.baidu.com/s/1o8n4VMU) link.

**Comment by Tetsujinfr** [comment]
This link works. Thanks for the amazingly fast answer. A star just for that.
Closing the "issue".
Tets
