### ISSUE TITLE
Train on own dataset

### ISSUE THREAD

**Issue by petwill** [TuSimple/mx-maskrcnn#28]
Any instructions on how to train it on our own dataset?

**Comment by huangzehao** [comment]
Hi, you can go through the code in 'rcnn/dataset' folder, and prepare your own dataset like cityscapes.

**Comment by hdjsjyl** [comment]
@huangzehao , whether the image sizes of dataset should be the same like cityscapes dataset. If one biggest size of images in my own dataset is 7127*7172, when I set the max_shape, it always has error for cuda memory fail. Thanks.
