### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ROIAlign' When I run demo.sh

### ISSUE THREAD

**Issue by EwanReton** [TuSimple/mx-maskrcnn#34]
I got some warning when I ran make:

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/cuda/include -I/usr/include/python2.7 -c gpu_nms.cpp -o build/temp.linux-x86_64-2.7/gpu_nms.o -Wno-unused-function
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from gpu_nms.cpp:499:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/nms_kernel.o build/temp.linux-x86_64-2.7/gpu_nms.o -L/usr/local/cuda/lib64 -Wl,-R/usr/local/cuda/lib64 -lcudart -o /home/lzq12138/lkd/maskrcnn/mx-maskrcnn/rcnn/cython/gpu_nms.so
cd rcnn/pycocotools; python2 setup.py build_ext --inplace; rm -rf build; cd ../../
Warning: Extension name '_mask' does not match fully qualified name 'rcnn.pycocotools._mask' of '_mask.pyx'
Compiling _mask.pyx because it depends on /usr/local/lib/python2.7/dist-packages/Cython/Includes/numpy/__init__.pxd.

I can run bash scripts/train_alternate.sh successfully ,then I  canceled the train with ctrl+c and trun to bash scripts/demo.sh 

Error in CustomOp.forward: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mxnet/operator.py", line 782, in forward_entry
    aux=tensors[4])
  File "/home/lzq12138/lkd/maskrcnn/mx-maskrcnn/rcnn/PY_OP/fpn_roi_pooling.py", line 76, in forward
    roi_pool = mx.nd.ROIAlign(feat_dict['stride%s' % s], _rois, (self._pool_h, self._pool_w), 1.0 / float(s))
AttributeError: 'module' object has no attribute 'ROIAlign'

[00:34:38] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [00:34:38] src/operator/custom/custom.cc:293: Check failed: reinterpret_cast<CustomOpFBFunc>(params.info->callbacks[kCustomOpForward])( ptrs.size(), ptrs.data(), tags.data(), reinterpret_cast<const int*>(req.data()), static_cast<int>(ctx.is_train), params.info->contexts[kCustomOpForward]) 

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x272c4c) [0x7f1961857c4c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x33ffaf) [0x7f1961924faf]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x20ef112) [0x7f19636d4112]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXExecutorForward+0x15) [0x7f1963665675]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f19d312ce40]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f19d312c8ab]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f19d333c3df]
[bt] (7) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f19d3340d82]
[bt] (8) python2(PyObject_Call+0x43) [0x4b0cb3]
[bt] (9) python2(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]

**Comment by huangzehao** [comment]
Hi, please refer this issue https://github.com/TuSimple/mx-maskrcnn/issues/15, thanks.
