### ISSUE TITLE
Check failed: allow_null  LocalFileSystem: fail to open "model/resnet-50-0000.params"

### ISSUE THREAD

**Issue by pythonnewer** [TuSimple/mx-maskrcnn#35]
mxnet.base.MXNetError: [22:47:15] src/io/local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "model/resnet-50-0000.params"

**Comment by Zehaos** [comment]
Hi, please download Resnet-50 pretrained model first, refer to [step 2](https://github.com/TuSimple/mx-maskrcnn#preparation-for-training).

**Comment by pythonnewer** [comment]
thank you  i download model but path is not scrips/model  it is /rcnn/utils/

**Comment by huangzehao** [comment]
@pythonnewer Did you solve this problem?

**Comment by winstywang** [comment]
Close due to inactive status. Please reopen it if needed.
