### ISSUE TITLE
demo problem

### ISSUE THREAD

**Issue by feiwenbo** [TuSimple/mx-maskrcnn#36]
mkdir: cannot create directory 'data/cityscape/results/': File exists
Namespace(dataset='Cityscape', dataset_path='data/cityscape', epoch=0, gpu=0, has_rpn=True, image_set='val', network='resnet_fpn', prefix='model/final', proposal='rpn', result_path='data/cityscape/results/', root_path='data', shuffle=False, thresh=0.001, vis=False)
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8],
 'CLASS_ID': [0, 24, 25, 26, 27, 28, 31, 32, 33],
 'FIXED_PARAMS': ['conv0', 'stage1', 'gamma', 'beta'],
 'FIXED_PARAMS_SHARED': ['conv0',
                         'stage1',
                         'stage2',
                         'stage3',
                         'stage4',
                         'P5',
                         'P4',
                         'P3',
                         'P2',
                         'gamma',
                         'beta'],
 'NUM_ANCHORS': 3,
 'NUM_CLASSES': 9,
 'PIXEL_MEANS': array([0, 0, 0]),
 'RCNN_FEAT_STRIDE': [32, 16, 8, 4],
 'ROIALIGN': True,
 'RPN_FEAT_STRIDE': [64, 32, 16, 8, 4],
 'SCALES': [(1024, 2048)],
 'TEST': {'BATCH_IMAGES': 1,
          'HAS_RPN': True,
          'NMS': 0.3,
          'PROPOSAL_MIN_SIZE': [64, 32, 16, 8, 4],
          'PROPOSAL_NMS_THRESH': 0.7,
          'PROPOSAL_POST_NMS_TOP_N': 2000,
          'PROPOSAL_PRE_NMS_TOP_N': 20000,
          'RPN_MIN_SIZE': [64, 32, 16, 8, 4],
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 1000,
          'RPN_PRE_NMS_TOP_N': 6000},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_IMAGES': 1,
           'BATCH_ROIS': 256,
           'BBOX_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZATION_PRECOMPUTED': False,
           'BBOX_REGRESSION_THRESH': 0.5,
           'BBOX_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_WEIGHTS': array([ 1.,  1.,  1.,  1.]),
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'RPN_BATCH_SIZE': 256,
           'RPN_BBOX_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': [64, 32, 16, 8, 4],
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALE': True,
           'SCALE_RANGE': [0.8, 1]}}
num_images 500
cityscape_val gt roidb loaded from data/cache/cityscape_val_gt_roidb.pkl
scripts/demo.sh: line 24: 31359 Segmentation fault      (core dumped) python demo_mask.py --network resnet_fpn --dataset ${DATASET} --image_set ${TEST_SET} --prefix ${PREFIX} --result_path ${RESULT_PATH} --has_rpn --epoch 0 --gpu 0
This is my running log, I have finished the mxnet install, but when I run the demo.sh, I met this problem, anyone helps?

**Comment by huangzehao** [comment]
`mkdir: cannot create directory 'data/cityscape/results/': File exists
`
Delete 'data/cityscape/results/' and run again.

**Comment by ZongweiZhou1** [comment]
I dont think it is the file problem as I can run with the same info: 'mkdir: cannot create directory 'data/cityscape/results/': File exists' , so maybe some path or gpu are not set correctly.

**Comment by Tetsujinfr** [comment]
trying some basics, user access right issue maybe, are you logged as root?
Tets

**Comment by huangzehao** [comment]
Hi, try latest version. We add `-p` flag to avoid mkdir error.

**Comment by feiwenbo** [comment]
thank you for help, but it is not the file problem, I alos use the root.
