### ISSUE TITLE
make cython failed

### ISSUE THREAD

**Issue by oyty** [TuSimple/mx-maskrcnn#37]
When i made the cython, it abort error message below, I run this in virtual machine, I know it's a problem about the gpu or cpu, i just don't know how to fix it, Someone can help me?

cd rcnn/cython/; python setup.py build_ext --inplace; rm -rf build; cd ../../
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 46, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
EnvironmentError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
cd rcnn/pycocotools; python setup.py build_ext --inplace; rm -rf build; cd ../../
Warning: Extension name '_mask' does not match fully qualified name 'rcnn.pycocotools._mask' of '_mask.pyx'
running build_ext

**Comment by huangzehao** [comment]
> EnvironmentError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME

Please check if you installed cuda successfully.

**Comment by jamesguoxin** [comment]
Do I have to install CUDA stuff for running this code? Is there any CPU version just for testing? THX

**Comment by jamesguoxin** [comment]
@huangzehao

**Comment by huangzehao** [comment]
Hi, @jamesguoxin , I recommend you install CUDA and test this code with GPU. We didn't test this code in CPU.

**Comment by jamesguoxin** [comment]
Thanks @huangzehao
