### ISSUE TITLE
How to evaluate the result?

### ISSUE THREAD

**Issue by ypflll** [TuSimple/mx-maskrcnn#38]
Hi, thank u very much for sharring. I run your demo and successfully segment 500 pictures--the result is really wonderfully!

However, how can I get the accuracy (as u mention in your table, u get a average accuracy of 26.2 on test set)?

**Comment by Zehaos** [comment]
Hi, @ypflll 
To eval on val set, you can refer to [preparation-for-evaluation](https://github.com/TuSimple/mx-maskrcnn#preparation-for-evaluation).
To eval on test set, you should have a account in https://www.cityscapes-dataset.com/, sign in and then upload the result file.

**Comment by ypflll** [comment]
I tried the val set and get 31.3 AP and 55.6 AP50. 
Thanks :)

**Comment by winstywang** [comment]
Glad to know that you have reproduced the results :-)
