### ISSUE TITLE
Out of array boundary?

### ISSUE THREAD

**Issue by chenjx1005** [TuSimple/mx-maskrcnn#4]
https://github.com/TuSimple/mx-maskrcnn/blob/36910cfe980e99ae63f085ee762191c90a38f2ce/rcnn/CXX_OP/roi_align.cu#L77-L78
the max possible value of `hlow` seems to be `height-1`, and the max value of `hhigh` is `height`. So is there some risk that the most bottom or right value out of feature array boundary?

Also, in these two lines,
https://github.com/TuSimple/mx-maskrcnn/blob/36910cfe980e99ae63f085ee762191c90a38f2ce/rcnn/CXX_OP/roi_align.cu#L86-L87
`hlow` is never equal to  `hhigh` and denominator seems always be 1.

**Comment by Zehaos** [comment]
Yes, you are right~ I have fix it.
