### ISSUE TITLE
 error "has no attribute 'cv'   cv2.cvtColor(im, cv2.cv.CV_RGB2BGR) 

### ISSUE THREAD

**Issue by Vitoria-Huang** [TuSimple/mx-maskrcnn#41]
##  I get the error "Has no attribute 'cv' " in the line " im = cv2.cvtColor(im, cv2.cv.CV_RGB2BGR)", when I run demo.sh . Can anyone solve it ? thanks！

**Comment by ZongweiZhou1** [comment]
replace 'cv2.cv.CV_RGB2BGR' with 'cv2.COLOR_RGB2BGR' cause your opencv version maybe >3.0 and 'cv2.cv.CV_RGB2BGR' is used in version <3.0

**Comment by Vitoria-Huang** [comment]
@ZongweiZhou1  Yes, you are right! The error has disappeared as what you say! Thanks!
