### ISSUE TITLE
train the cityscape dataset with RCNNL1Loss=nan?

### ISSUE THREAD

**Issue by iFighting** [TuSimple/mx-maskrcnn#42]
when training the dataset in stage TRAIN RCNN WITH RPN INIT AND DETECTION (after COMBINE RPN2 WITH RCNN1), the RCNNL1Loss is always nan, i try several times, and i set the base_lr really low, it is always nan,
environment is  p40/8 gpu

**Comment by Zehaos** [comment]
@iFighting Could you provide your training configuration?

**Comment by iFighting** [comment]
i use your default config, but i use 8 gpus
other base_lr i use is 0.004, 0.002,0.001,0.0005,  but all get nan

**Comment by Zehaos** [comment]
How was your training, is it smooth from step 1 to step 3?

**Comment by iFighting** [comment]
i found the problem, the rpn data is not matched with the mask data
solved, thanks @Zehaos

**Comment by tkuanlun350** [comment]
@iFighting  Hi ! 
I am training with my own data and encounter the same problem.
RCNNL1 loss become **nan** at the first iteration in maskrcnn. and mask loss is very low.

**ex:RCNNLogLoss=2.330018,   RCNNL1Loss=nan, MaskACC=0.999521,       MaskLogLoss=0.000710**

Can you provide more detail about **"rpn data is not matched with the mask data"** ? 

Thank you very much !

**Comment by tkuanlun350** [comment]
Sorry I found that the order of bounding box is actually [xmin, ymin, xmax, ymax]. Silly mistake :(

**Comment by lt573152873** [comment]
@tkuanlun350 Have you solved the problem?

**Comment by dingfg** [comment]
I also encountered the same problem. How do you specifically solve it? Please
