### ISSUE TITLE
I got no mask on demo scripts

### ISSUE THREAD

**Issue by greatgeekgrace** [TuSimple/mx-maskrcnn#45]
hi, I put our data as cityscape format. And train it successfully and get the final.params model.

But when I evaluate it, got the following result:
##################################################
what           :             AP         AP_50%
##################################################
person         :          0.000          0.000
rider          :            nan            nan
car            :            nan            nan
truck          :            nan            nan
bus            :            nan            nan
train          :            nan            nan
motorcycle     :            nan            nan
bicycle        :            nan            nan
--------------------------------------------------
average        :          0.000          0.000

And got no mask on demo scripts.
would you please help to suggest the problem happened in train process or some other reanson.

Thank you.

**Comment by huangzehao** [comment]
Have you tried our model in cityscapes datasets?
