### ISSUE TITLE
src/storage/storage.cc:59: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: invalid device ordinal

### ISSUE THREAD

**Issue by DevinCheung** [TuSimple/mx-maskrcnn#52]
I encountered the above error while training. How could I solve it? THX!

**Comment by huangzehao** [comment]
Hi, you have to check how many GPU's are available in your system first. In our training bash, we use four gpu to train.
https://github.com/TuSimple/mx-maskrcnn/blob/master/scripts/train_alternate.sh#L21

**Comment by DevinCheung** [comment]
@huangzehao Hi, I have two GPU in my system. But right now only one is available. Where shall I modify?

**Comment by huangzehao** [comment]
@DevinCheung 
`--gpu 0` and divide the learning rate by 4.
https://github.com/TuSimple/mx-maskrcnn/blob/master/rcnn/config.py#L108

**Comment by DevinCheung** [comment]
@huangzehao Got it. Thanks a lot!
