### ISSUE TITLE
Scale Problem

### ISSUE THREAD

**Issue by ChenFengYe** [TuSimple/mx-maskrcnn#57]
I find that your code may not correct when using multi-scale dataset.
After I fix the scale error about un-used Config.scale. The network always get nan loss,  when training the multi-scale, especially when changing scale size from [1024, 2048] to [640, 1024].

BTW, I do change the value of config.TRAIN.SCALE to True. And the core/tester.py line160 and line226 will get error on evaluation. If you do not set "scale" into function "im_detect_mask"!

**Comment by Zehaos** [comment]
@ChenFengYe 
config.SCALE only used in training. 

You can use the tool below to help verify your label.
https://gist.github.com/Zehaos/6b0fc81a606944310ce2bd93f7fc2031

**Comment by ChenFengYe** [comment]
@Zehaos Sorry, Did I forget to load something? I get error
> Traceback (most recent call last):
  File "checkLabel.py", line 4, in <module>
    from rcnn.pycocotools.mask import decode
  File "/home/liyuw/Geonet-mx-maskrcnn/rcnn/pycocotools/mask.py", line 3, in <module>
    import _mask
ImportError: /home/liyuw/Geonet-mx-maskrcnn/rcnn/pycocotools/_mask.so: undefined symbol: PyFPE_jbuf

**Comment by Zehaos** [comment]
@ChenFengYe Try to rebuild the pycocotools.

**Comment by ChenFengYe** [comment]
@Zehaos I don't know how to rebuild this (>_< )

**Comment by Zehaos** [comment]
rm *.so *.c *.cpp in pycocotools folder first, and then run 'make' under root folder.

**Comment by ChenFengYe** [comment]
@Zehaos is that right？The masks and images match quite well. However, the images get totally different size with masks. As I mentioned, My datasets are multi-scale.

**Comment by Zehaos** [comment]
@ChenFengYe The mask label is a 28*28 mask. So it don't worry about the scale of it.

**Comment by ChenFengYe** [comment]
@Zehaos I must invite you for dinner. If the CVPR is done! Thanks a lot!

**Comment by ChenFengYe** [comment]
Oh, But the error I mentioned
the core/tester.py line160 and line226 will get error on evaluation. If you do not set "scale" into function "im_detect_mask"!

**Comment by Zehaos** [comment]
@ChenFengYe We only rescle the image in training. It is not reasonable to do that in testing. May be there are other mistake of your own dataset.

**Comment by ChenFengYe** [comment]
@Zehaos Does "--has_rpn" mean loading get_roi from annotation ??
references
> demo_maskrcnn.py -- line 24, line 29

**Comment by Zehaos** [comment]
@ChenFengYe Send me an E-mail.

**Comment by ChenFengYe** [comment]
@Zehaos Get my email? I send it to your xxx.scu@gmail.com.
