### ISSUE TITLE
Some question about the mask rcnn code?

### ISSUE THREAD

**Issue by chengshuai** [TuSimple/mx-maskrcnn#68]
Thanks you for the nice job!
 I have some question:
(1)In the symbol_mask_fpn.py, after fpn_roi_pooling layer, the two fully connection layer is connected for cls and bboxes, why not use two 1024 convolution layer(paper is two convolution layer)?
(2)For effcinecy, the end2end faster rcnn will replace the alternate 
(3)The mask rcnn is based on faster rcnn, will complete base on R-FCN?

**Comment by Zehaos** [comment]
Hi, @chengshuai 
(A1): Paper is two fc layer. Please refer to figure 3, page 4.
(A2): Of course e2e is elegant and efficient. We do try e2e at first, but got bad result.
(A3): No plan to do that.

**Comment by chengshuai** [comment]
Hi @Zehaos 

Thank your for your reply! For (1), I have understood.

**Comment by Zehaos** [comment]
More detail about e2e training, please refer to #72

**Comment by chengshuai** [comment]
@Zehaos 

Ok, Thanks!
