### ISSUE TITLE
RoIAlign implementation bug?

### ISSUE THREAD

**Issue by nnop** [TuSimple/mx-maskrcnn#74]
While reading the implementation of RoIAlign, I came to those codes:

https://github.com/TuSimple/mx-maskrcnn/blob/eb6f4374cee97599bc666d6c29de165753276c5c/rcnn/CXX_OP/roi_align.cu#L70-L96

The variable `bottom_index`(L70) is for indexing the 4 sampling points in each bin. 
The problem is, it increments at the very beginning of the sampling loop (L76) before being saved to the maximum index `maxidx` (L93). This would cause a shift of pooling the position. 
Is this a bug?

**Comment by Zehaos** [comment]
Hi, @nnop 
This is not a bug. We do the same thing in the backward part(increments at the very beginning of the sampling loop [roi_align.cu#L206](https://github.com/TuSimple/mx-maskrcnn/blob/eb6f4374cee97599bc666d6c29de165753276c5c/rcnn/CXX_OP/roi_align.cu#L206)) .

**Comment by nnop** [comment]
Why does `bottom_index` not record the current index in the loop?

**Comment by nnop** [comment]
I see, thanks.
