### ISSUE TITLE
how to train using my own data?

### ISSUE THREAD

**Issue by perp** [TuSimple/mx-maskrcnn#79]
I can produce image and annotations json file.
how to prepare data as cityscape format and start trainning then?
1. Any necessary to generate gtFine_color.png , gtFine_instanceIds.png  and gtFine_labelIds.png and how ? 
2. I see in image list folder a train.lst have two image paths, how to generate the last image, eg _gtFine_labelTrainIds.png

Thanks in advance!

**Comment by ctgushiwei** [comment]
@perp how to train own data?

**Comment by winstywang** [comment]
This repo is out of date. Please refer to https://github.com/TuSimple/simpledet for the latest
