### ISSUE TITLE
Will the pose estimation be supported by mx-maskrcnn?

### ISSUE THREAD

**Issue by PhanTask** [TuSimple/mx-maskrcnn#80]
Really impressed by the performance by maskrcnn on human pose estimation. So will the pose estimation be supported by mx-maskrcnn in the future version?

**Comment by winstywang** [comment]
Hi, thanks for the interest. Unfortunately, due to limited interns, we cannot provide such extension. You are welcomed to contribute to this repo.

**Comment by hdjsjyl** [comment]
@winstywang , I am trying pose estimation. I prepare mask and training as the mask prediction part in your code. The training accuracy is 1.00, and loss is 0 from begining. So can you give me some advice about that? Any advice will be appreciated. Thank you.
