### ISSUE TITLE
MaskAcc Always equals 1.0 

### ISSUE THREAD

**Issue by perp** [TuSimple/mx-maskrcnn#87]
It seems detection result is ok, but MaskAcc=1.0 and MaskLogLoss=0.0 from start training util end training.
what did I miss?
![123](https://user-images.githubusercontent.com/2972254/33538353-da87821c-d8fb-11e7-9d06-a8b8b6dea404.png)

**Comment by perp** [comment]
Did input data has image with only background label infect?

**Comment by xxradon** [comment]
I have got the same problem,I guess maybe the reason for that is  the instances  have  very large areas or masks for your input image.

**Comment by perp** [comment]
@xxradon thanks for you reply, I have negative samples which mask is entire image. Do I need to delete these samples?

**Comment by perp** [comment]
I delete these negative samples and the result is fine
