### ISSUE TITLE
ResNet structure problem

### ISSUE THREAD

**Issue by bilipa** [TuSimple/mx-maskrcnn#89]
I found your ResNet structure is BN->ReLU->Conv(1)
But why did you not use this structure: Conv->BN->ReLU(2)
Does the (1) structure is better than (2) in your experiment?
Thanks.

structure 1 mentioned in:  https://arxiv.org/pdf/1603.05027.pdf

**Comment by huangzehao** [comment]
Hi, we didn't experiment the difference between (2) resnet and (1) pre-act resnet.
We adopt (1) because it is a common choice in mxnet. 
The pretrained model is provided by https://github.com/tornadomeet/ResNet .
Thanks.

**Comment by bilipa** [comment]
Thanks, I see.
