### ISSUE TITLE
Has anyone get correct output by running bash scripts/demo_single_image.sh (test single image)

### ISSUE THREAD

**Issue by Jinnaouc** [TuSimple/mx-maskrcnn#90]
I run bash scripts/demo_single_image.sh, but the out put is the same with the original image.

**Comment by mrmitzh** [comment]
It seems that there is something wrong with the argparser when dealing with bool type. So if you are running it you may need to modify the rcnn/tools/demo_single_image.py and set demo_maskrcnn(network = args.network,
                  ctx = ctx,
                  prefix = args.prefix,
                  epoch = args.epoch,
                  img_path = args.image_name,
                  vis= args.vis -->vis= True or False depends on your request.
                  has_rpn = True,
                  thresh = args.thresh)

**Comment by huangzehao** [comment]
Solved by https://github.com/TuSimple/mx-maskrcnn/commit/8e9f95944af9477ab7438f149d5a9ceaa9e14b1e.
